<a href="https://colab.research.google.com/github/vishnupal/ML/blob/master/day1ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!cat /etc/issue #for checking os  #theano

Ubuntu 18.04.3 LTS \n \l



In [0]:
!free -m  #for checking ram in GB


              total        used        free      shared  buff/cache   available
Mem:          13022         517       10588           0        1916       12235
Swap:             0           0           0


In [0]:
!lscpu #for CPU check


Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:            0
CPU MHz:             2300.000
BogoMIPS:            4600.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            46080K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs 

In [0]:
#we are going to use Numpy
import numpy as np

[i for i in dir(np)  if 'arr' in i]

['array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfarray',
 'asfortranarray',
 'broadcast_arrays',
 'chararray',
 'compare_chararrays',
 'get_array_wrap',
 'ndarray',
 'numarray',
 'recarray']

In [0]:
a1 =np.array([2,6,76,8])
a1

array([ 2,  6, 76,  8])

In [0]:
#creating 2D array
arr2D=np.array([[1,6,7],[3,5,9],[6,9,5],[3,11,2]])
arr2D

array([[ 1,  6,  7],
       [ 3,  5,  9],
       [ 6,  9,  5],
       [ 3, 11,  2]])

In [0]:
#to print 1st row
arr2D[0]

array([1, 6, 7])

In [0]:
#to print firstelement of 2D array
arr2D[0,0]

1

In [0]:
arr2D[0][0]

1

In [0]:
#first 2 row
arr2D[0:2]

array([[1, 6, 7],
       [3, 5, 9]])

In [0]:
# to print 1at column
arr2D[:,0]

array([1, 3, 6, 3])

In [0]:
#first two columns
arr2D[:,:2]

array([[ 1,  6],
       [ 3,  5],
       [ 6,  9],
       [ 3, 11]])

In [0]:
arr2D[1:3,1:]

array([[5, 9],
       [9, 5]])

In [0]:
arr2D[1:3,0::2]

array([[3, 9],
       [6, 5]])

In [0]:
#now next task
arr2D[1:3,[0,2]]

array([[3, 9],
       [6, 5]])

In [0]:
arr2D[1::2,[0,2]]

array([[3, 9],
       [3, 2]])

In [0]:
arr2D[[1,3],[0,2]]

array([3, 2])

In [0]:
#math ops
arr2D

array([[ 1,  6,  7],
       [ 3,  5,  9],
       [ 6,  9,  5],
       [ 3, 11,  2]])

In [0]:
arr2D+6

array([[ 7, 12, 13],
       [ 9, 11, 15],
       [12, 15, 11],
       [ 9, 17,  8]])

In [0]:
np.sin(arr2D)

array([[ 0.84147098, -0.2794155 ,  0.6569866 ],
       [ 0.14112001, -0.95892427,  0.41211849],
       [-0.2794155 ,  0.41211849, -0.95892427],
       [ 0.14112001, -0.99999021,  0.90929743]])

In [0]:
y=arr2D

In [0]:
y[0,0]=5
y

array([[ 5,  6,  7],
       [ 3,  5,  9],
       [ 6,  9,  5],
       [ 3, 11,  2]])

In [0]:
arr2D

array([[ 5,  6,  7],
       [ 3,  5,  9],
       [ 6,  9,  5],
       [ 3, 11,  2]])

In [0]:
#finall about numpy
#10 7 with all zeros
np.zeros((7,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [0]:
#one 
np.ones((12,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
np.full((12,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [0]:
#seaborn,matplotlip,gplot,plotly
